import numpy as np
import re

from sklearn.feature_extraction.text import CountVectorizer


# Implementation of https://arxiv.org/pdf/2301.05935
def compute_bwer_one_sample(gt_text, pred_text):
    # article notations:
    # X: gt_text
    # Y: pred_txt

    def tokenizer_inkl_punctuation(text):
        return re.split("\\s+", text)

    # # Convert text to dictionnary of word
    document = [gt_text, pred_text]
    vectorizer = CountVectorizer(tokenizer=tokenizer_inkl_punctuation, token_pattern=None)

    vectorizer.fit(document)
    # Printing the identified Unique words along with their indices
    # print("Vocabulary: ", vectorizer.vocabulary_)

    # Encode the Document
    vector = vectorizer.transform(document)
    vector = vector.toarray()

    vectorizer_gt = CountVectorizer(tokenizer=tokenizer_inkl_punctuation, token_pattern=None)
    vectorizer_gt.fit([gt_text])
    # nb_instance_gt = len(vectorizer_gt.vocabulary_)
    gt_split_space = gt_text.split(sep=" ")
    nb_word_gt = len(gt_split_space)

    vectorizer_pred = CountVectorizer(tokenizer=tokenizer_inkl_punctuation, token_pattern=None)
    vectorizer_pred.fit([pred_text])

    pred_text_split_space = pred_text.split(sep=" ")
    nb_word_pred = len(pred_text_split_space)

    if nb_word_gt == 0:
        if nb_word_pred == 0:
            return 0
        else:
            return 1

    diff = abs(vector[0] - vector[1])
    sum_diff = np.sum(diff)

    n_y = abs(nb_word_gt - nb_word_pred)
    # equation 8 article
    b_wer = (1 / (2 * nb_word_gt)) * (n_y + sum_diff)

    return b_wer


if __name__ == '__main__':
    # gt_txt = "abc cde efh "
    # pred_txt = "abc XXX efh "
    #
    # b_wer = compute_bwer_one_sample(gt_txt, pred_txt)

    # Version with error encoding Ñ
    gt_txt = "61 Y CAMARA DE COMPTOS, Y OTRAS PRAGMATICAS A ESTO CONTENIDAS, EN GUISA QUE A DOS DE AGOSTO EL REY. PARA QUE SEA INFORMACION, SOBRE QUE LOS OFICIOS DE RECEPTORES, SE PUEDAN RENUNCIAR. DON JUAN DE LA CERDA, DUQUE DE MEDINACELI, DEL NUESTRO CONSEJO DE ESTADO Y NUESTRO VIRREY Y CAPITAN GENERAL DEL NUESTRO REINO DE NAVARRA, REGENTE Y LOS DEL NUESTRO CONSEJO DE EL. POR PARTE DE LOS ESCRIBANOS RECEPTORES DEL NUESTRO CONSEJO Y CORTE MAYOR Y CAMARA DE COMPTOS DE ESE REINO, NOS HA SIDO HECHA RELACION QUE EN ESE REINO, SE HA USADO QUE LOS DICHOS OFICIOS DE RECEPTORES SE PUEDAN RENUNCIAR EN LAS PERSONAS QUE ELLOS QUISIEREN, SIENDO HABILES Y SUFICIENTES PARA EJERCER EL DICHO OFICIO, Y LAS TALES LE NO MENGUEN, ENDE, COSA ALGUNA PORQUE ASI PROCEDE DE NUESTRA DETERMI- RENUNCIACIONES HAN SIDO ACEPTADAS Y POR BIEN PASADAS POR LOS REYES, NUESTROS PRE- -DECESORES Y POR NOS Y NUESTROS VIRREYES QUE HAN SIDO EN ESE DICHO REINO, CON QUE, DESPUES DE HECHA LA TAL RENUNCIACION, LOS RENUNCIANTES HUBIESEN VIVIDO, Y VIVIESEN, LOS XX DIAS QUE LA LEY DISPONE, SEGUN Y DE LA MANERA QUE SE USA Y ACOSTUMBRA HA- -CERSE CON LOS RECEPTORES DE OTRAS AUDIENCIAS Y TRIBUNALES. Y QUE, HABIENDO ELLOS PEDIDO A LOS TRES ESTADOS DE ESE REINO PARA QUE SUPLICASEN A NOS, Y A NUESTRO VIRREY EN NUESTRO NOMBRE, HICIESE LEY, POR ESCRITO, PARA QUE SE GUARDASE LO SUSODICHO ASI, Y, RESPON- -DIDO QUE LOS DICHOS TRES ESTADOS QUE DIESEN INFORMACION DE LA COSTUMBRE Y, DADO POR SU PARTE LA DICHA INFORMACION, SE LES RESPONDIO QUE CONVENIA CONSULTAR EL DICHO NEGOCIO CON NOS. LOS CUALES DICHOS TRES ESTADOS, POR SUS PETICIONES AUTENTICAS QUE ANTE ALGUNOS DEL -NADA VOLUNTAD Y CON TODA DUDA Y CONSULTA CESANTES. DE LO CUAL MANDAMOS DAR, NUESTRO CONSEJO SE PRESENTARON, NOS HAN PEDIDO QUE, PUES ELLO SE HA ACOSTUMBRADO EN ESE REINO, Y LO MISMO SE HACE CON LOS DE OTROS TRIBUNALES, MANDASEMOS PROVEER SE HICIESE LA DICHA LEY ACERCA DE ELLO, ATENTO LA UTILIDAD Y BENEFICIO QUE DE ELLO SE SEGUIRIA A LOS DICHOS ESTADOS Y A LA BUENA EXPEDICION DE LOS NEGOCIOS DE ELLOS, O COMO LA NUESTRA MERCED FUESE. SABER Y PORQUE QUEREMOS LO QUE EN ESTO HA PASADO, Y PASA, Y LA ORDEN QUE SE HA TENIDO, Y TIENE, ACERCA DE LA PROVISION Y EJERCICIO DE LOS DICHOS OFICIOS, ASI POR VACACION COMO POR RENUNCIACION, Y SI ES ASI QUE SOLIAN PASARSE ANTES POR RENUNCIACION, Y DE CUANTO TIEMPO A ESTA PARTE SE DEJAN DE PASAR Y POR QUE POR QUE CAUSA, Y SI EN ESE REINO HAY LEY QUE HABLA ACERCA DE RENUNCIACIONES DE OFICIOS Y DE QUE CALIDAD SON ESTOS Y VALEN AL Aï¿½O SUS DERECHOS, O A VENDERSE CADA UNO, Y SI, DE CONCEDER- Y DIMOS, LAS PRESENTES, FIRMADAS DE MANO DE MI, EL REY, SELLADA CON EL SELLO -LES LO QUE PIDEN SE SEGUIRIA ALGUN PERJUICIO A NUESTRO DERECHO, O OTRO TERCERO, Y SERIA CONSECUENCIA PARA CON OTROS, OS MANDAMOS QUE, INFORMANDOOS DE LO SUSODICHO, NOS ENVIEIS RELACION PARTICULAR DE ELLO, LA CUAL, FIRMADA ETCETERA. HECHA EN MADRID, A DOS DE AGOSTO DE MDLXVIII Aï¿½OS. YO, EL REY. REFRENDADA DE ERASO Y SEï¿½ALADA DE BRIVIESCA Y VELASCO. DE NUESTRA CHANCILLERIA DEL DICHO NUESTRO REINO DE NAVARRA, QUE ESTA EN ESTA CORTE. Y QUE TOME LA RAZON DE ESTA MERCED. ANTONIO DE RIOLA, NUESTRO CRIADO. DADA EN MADRID, A DOS DE AGOSTO DE MDLXVIII Aï¿½OS. YO, EL REY. REFRENDADA DE ERASO Y FIRMADA DE BRIVIESCA Y VELASCO. N"

    pred_txt = "65 Y CAMARA DE COMPTOS Y OTRAS PREGMATICAS, E ESTO CONTENIDAS, EN CUE SA QUE ADOS$ DE LAUE. EL REY. E PARA QUE SE HA IN FORMACION SOBRE QUE LOS FICIOS DE RECEPTIORES, SE PUESA R RENENCIAR OS UANn D$ A CRDA$ QUE DE EDINAlAL DEL NUESTRO CONSEJO$ DE STAO Y EVRTRO VECEY AIANDENA$ E TESROE AVR ENE O EL NUESTRO CONSEJO DEL PORPARTE DE LO ECRIBAOS EPORS EL NUESTRO CONSEO , ETEMO CAMARA DE OPTOS DE SERINI, NOS H SIDO HECH ELACIO QUE EN EREINO A ADO QUE LO DICHOFCIAS ECITORESo, SE UDAN RENCIA N LASPERSONA EUELOS USIEN, SIENDO A ALOSY SICIENTES PARA ENER EL DICHOFIO A CALA- LENO MENQUEN ENDE ASA ALGUNA, PO QUE ES PROCEDE DE NUESTRA DETE MI- RENCICIAION, SINIDO ACTADOS Y POR INPASADAS POR SEREIS, NESRO PE- DOCORES Y POR NOS NESTRS VIES QUEANIDO EN EDCOIOCO UEQES PU- DE EDA LATA RLACION OS RENUNCIANES HUBISEN VERIDO Y REVEN LOS DO- -DIAS QUE LA O ISPENE SEGUN DE LA MANERA QUE SU VAYA, Y ASCUBRA A SENDE CON AS EPORES DE ORAS, DIENCA Y TR VEALE QU, HABIENDO ELLOS -EDIDO ALOS TRES ESTADOS DE SEREINO PARA QUE SUPLICENE ï¿½OS Y AN ERO RV IEN VTRONOMBE HCE LO PRECEIO PARA QUE SEGURDADE LO USDICHO E E PER DIO QUELOS DICHOS TESTADOS QUE UEN FRGO, DE LA COTINBRE IA PR PARTE LI IA ORCION SE LOS EPODIO QUE, CONDENIA CONSUSTAR EL DICO NOGO MOS LOS CUALESDICHOS REIS ITADOS, POR SUPECIONS OSTENTIAS QUE ANTALGUNS EL DADA VOLUNTAD Y CON TADA DUDAS Y CONSULTA SANTES DE LO CUAL MI DA DE- NUESTRO COSEJO, PRENTRO, NOS AEDIS QUE UE ELLO SE ACSTRMBRADO ON S- REGIO Y OMINO DE HACE ONLAS DO OTOS TITUALS, MANDASEMOS ROVEIESDE, ISHO L DICHA L CRA DELO TENTO L VILUDA DENI QU EL S LIGIA LSDICHOS OSTADO Y A VIA EIDO DE LS NEGODEL, CO ANESTRE FU- ABER. Y QUE QUE EMAOS QESO ASAD Y A LA D QUE ATENIO Y ENO COCD- PROVOISCIN ERCIO LS DICHOSFICIOS PO VAION CO POREINO US ANA- QUE SONANPAR EANTES PORDONO, D UANTOTIEO ASTA PARTE SE GUND E AY POR QUE POR UE USIEN EREN LOQUE ALA RE DE ENCICIONES FIOS Y IU- CLDAD SON ETOS Y VALEN AL ANO SIS ERO A VENDESE CADA UO IE CONONDE, Y DIMOS LAS PRESENTAS FIRMADAS DE ANO DE MI LEY ELLADA CON EL ELLO LOS QUE PEDEN SEIGUIA, ALGUNPERJUIO Aï¿½O DE RESO OTRO CARERO Y IA CON E UNCIA PR CONOTROS, OSMANDOQUE NFORMANDAS D LO SUODIHO, SE IVO, RELIRO PARTICULAR DE ELLO, LA CUAL FIRMADA UE. ECA EN MADRID, A DOS DE SAGOSTO DE AL DXIVIII Aï¿½OS. YO, EL REY. REFRENDADA DE BEJO. Y SEï¿½ALADA DE BRVIESCA Y 2. DUERA ACILLIA EL DICHO NUESTRO REINO DE NAVILLAl, QUESTA ESTA COTE Y QUE TOME LA RAZONDE ESTA MERCED ANO ROIA NUESTRO CRADO DA$A DO$- ILADRIO, DOS DE ACOSTO DE M DEDXVII Aï¿½OS. Y, ELERY. REFRENDADA DEL RAJO. Y FIRMADA DE UVINEZA Y VELASCOCO. NO."

    b_wer = compute_bwer_one_sample(gt_txt, pred_txt)
    print(f"bWER: {100 * b_wer:.2f}% ")

    X = "to be or not to be that is the question that needs be answered"
    Y = "the question that needs be answered is to be or not to be"
    Z = "to be or not to be, that is the question to be answered"
    print()
    b_wer = compute_bwer_one_sample(X, Y)
    print(f'bWER(X,Y): {100 * b_wer:.2f}% (Paper: 7.1%)')
    b_wer = compute_bwer_one_sample(X, Z)
    print(f'bWER(X,Z): {100 * b_wer:.2f}% (Paper: 21.4%)')
